[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cornserve"
description = "Easy, fast, and scalable agentic AI"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]
requires-python = ">=3.12"
dependencies = [
    "grpcio",
    "tyro",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["grpcio-tools", "black", "pyright", "ruff"]

[tool.setuptools.dynamic]
version = { attr = "cornserve.__version__" }

[tool.ruff]
line-length = 120

[tool.pyright]
exclude = [
    "**/*_pb2.py",
    "**/*_pb2_grpc.py",
]
